//
//Chunk Explorer, a platform for hosting and discovering Minecraft servers.
//Copyright (C) 2025 Yannic Rieger <oss@76k.io>
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU Lesser General Public
//License as published by the Free Software Foundation; either
//version 3 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//Lesser General Public License for more details.
//
//You should have received a copy of the GNU Lesser General Public License
//along with this program; if not, write to the Free Software Foundation,
//Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platformd/proxy/v1alpha1/service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListenersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadID    string                 `protobuf:"bytes,1,opt,name=workloadID,proto3" json:"workloadID,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenersRequest) Reset() {
	*x = CreateListenersRequest{}
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenersRequest) ProtoMessage() {}

func (x *CreateListenersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenersRequest.ProtoReflect.Descriptor instead.
func (*CreateListenersRequest) Descriptor() ([]byte, []int) {
	return file_platformd_proxy_v1alpha1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListenersRequest) GetWorkloadID() string {
	if x != nil {
		return x.WorkloadID
	}
	return ""
}

func (x *CreateListenersRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CreateListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenersResponse) Reset() {
	*x = CreateListenersResponse{}
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenersResponse) ProtoMessage() {}

func (x *CreateListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenersResponse.ProtoReflect.Descriptor instead.
func (*CreateListenersResponse) Descriptor() ([]byte, []int) {
	return file_platformd_proxy_v1alpha1_service_proto_rawDescGZIP(), []int{1}
}

type DeleteListenersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadID    string                 `protobuf:"bytes,1,opt,name=workloadID,proto3" json:"workloadID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenersRequest) Reset() {
	*x = DeleteListenersRequest{}
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenersRequest) ProtoMessage() {}

func (x *DeleteListenersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenersRequest.ProtoReflect.Descriptor instead.
func (*DeleteListenersRequest) Descriptor() ([]byte, []int) {
	return file_platformd_proxy_v1alpha1_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteListenersRequest) GetWorkloadID() string {
	if x != nil {
		return x.WorkloadID
	}
	return ""
}

type DeleteListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenersResponse) Reset() {
	*x = DeleteListenersResponse{}
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenersResponse) ProtoMessage() {}

func (x *DeleteListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_proxy_v1alpha1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenersResponse.ProtoReflect.Descriptor instead.
func (*DeleteListenersResponse) Descriptor() ([]byte, []int) {
	return file_platformd_proxy_v1alpha1_service_proto_rawDescGZIP(), []int{3}
}

var File_platformd_proxy_v1alpha1_service_proto protoreflect.FileDescriptor

const file_platformd_proxy_v1alpha1_service_proto_rawDesc = "" +
	"\n" +
	"&platformd/proxy/v1alpha1/service.proto\x12\x18platformd.proxy.v1alpha1\"H\n" +
	"\x16CreateListenersRequest\x12\x1e\n" +
	"\n" +
	"workloadID\x18\x01 \x01(\tR\n" +
	"workloadID\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x19\n" +
	"\x17CreateListenersResponse\"8\n" +
	"\x16DeleteListenersRequest\x12\x1e\n" +
	"\n" +
	"workloadID\x18\x01 \x01(\tR\n" +
	"workloadID\"\x19\n" +
	"\x17DeleteListenersResponse2\xfe\x01\n" +
	"\fProxyService\x12v\n" +
	"\x0fCreateListeners\x120.platformd.proxy.v1alpha1.CreateListenersRequest\x1a1.platformd.proxy.v1alpha1.CreateListenersResponse\x12v\n" +
	"\x0fDeleteListeners\x120.platformd.proxy.v1alpha1.DeleteListenersRequest\x1a1.platformd.proxy.v1alpha1.DeleteListenersResponseB>Z<github.com/spacechunks/explorer/api/platformd/proxy/v1alpha1b\x06proto3"

var (
	file_platformd_proxy_v1alpha1_service_proto_rawDescOnce sync.Once
	file_platformd_proxy_v1alpha1_service_proto_rawDescData []byte
)

func file_platformd_proxy_v1alpha1_service_proto_rawDescGZIP() []byte {
	file_platformd_proxy_v1alpha1_service_proto_rawDescOnce.Do(func() {
		file_platformd_proxy_v1alpha1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformd_proxy_v1alpha1_service_proto_rawDesc), len(file_platformd_proxy_v1alpha1_service_proto_rawDesc)))
	})
	return file_platformd_proxy_v1alpha1_service_proto_rawDescData
}

var file_platformd_proxy_v1alpha1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platformd_proxy_v1alpha1_service_proto_goTypes = []any{
	(*CreateListenersRequest)(nil),  // 0: platformd.proxy.v1alpha1.CreateListenersRequest
	(*CreateListenersResponse)(nil), // 1: platformd.proxy.v1alpha1.CreateListenersResponse
	(*DeleteListenersRequest)(nil),  // 2: platformd.proxy.v1alpha1.DeleteListenersRequest
	(*DeleteListenersResponse)(nil), // 3: platformd.proxy.v1alpha1.DeleteListenersResponse
}
var file_platformd_proxy_v1alpha1_service_proto_depIdxs = []int32{
	0, // 0: platformd.proxy.v1alpha1.ProxyService.CreateListeners:input_type -> platformd.proxy.v1alpha1.CreateListenersRequest
	2, // 1: platformd.proxy.v1alpha1.ProxyService.DeleteListeners:input_type -> platformd.proxy.v1alpha1.DeleteListenersRequest
	1, // 2: platformd.proxy.v1alpha1.ProxyService.CreateListeners:output_type -> platformd.proxy.v1alpha1.CreateListenersResponse
	3, // 3: platformd.proxy.v1alpha1.ProxyService.DeleteListeners:output_type -> platformd.proxy.v1alpha1.DeleteListenersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platformd_proxy_v1alpha1_service_proto_init() }
func file_platformd_proxy_v1alpha1_service_proto_init() {
	if File_platformd_proxy_v1alpha1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformd_proxy_v1alpha1_service_proto_rawDesc), len(file_platformd_proxy_v1alpha1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platformd_proxy_v1alpha1_service_proto_goTypes,
		DependencyIndexes: file_platformd_proxy_v1alpha1_service_proto_depIdxs,
		MessageInfos:      file_platformd_proxy_v1alpha1_service_proto_msgTypes,
	}.Build()
	File_platformd_proxy_v1alpha1_service_proto = out.File
	file_platformd_proxy_v1alpha1_service_proto_goTypes = nil
	file_platformd_proxy_v1alpha1_service_proto_depIdxs = nil
}
