// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platformd/checkpoint/v1alpha1/types.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointState int32

const (
	CheckpointState_RUNNING                     CheckpointState = 0
	CheckpointState_PULL_BASE_IMAGE_FAILED      CheckpointState = 1
	CheckpointState_CONTAINER_WAIT_READY_FAILED CheckpointState = 2
	CheckpointState_CONTAINER_CHECKPOINT_FAILED CheckpointState = 3
	CheckpointState_PUSH_CHECKPOINT_FAILED      CheckpointState = 4
	CheckpointState_COMPLETED                   CheckpointState = 5
)

// Enum value maps for CheckpointState.
var (
	CheckpointState_name = map[int32]string{
		0: "RUNNING",
		1: "PULL_BASE_IMAGE_FAILED",
		2: "CONTAINER_WAIT_READY_FAILED",
		3: "CONTAINER_CHECKPOINT_FAILED",
		4: "PUSH_CHECKPOINT_FAILED",
		5: "COMPLETED",
	}
	CheckpointState_value = map[string]int32{
		"RUNNING":                     0,
		"PULL_BASE_IMAGE_FAILED":      1,
		"CONTAINER_WAIT_READY_FAILED": 2,
		"CONTAINER_CHECKPOINT_FAILED": 3,
		"PUSH_CHECKPOINT_FAILED":      4,
		"COMPLETED":                   5,
	}
)

func (x CheckpointState) Enum() *CheckpointState {
	p := new(CheckpointState)
	*p = x
	return p
}

func (x CheckpointState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointState) Descriptor() protoreflect.EnumDescriptor {
	return file_platformd_checkpoint_v1alpha1_types_proto_enumTypes[0].Descriptor()
}

func (CheckpointState) Type() protoreflect.EnumType {
	return &file_platformd_checkpoint_v1alpha1_types_proto_enumTypes[0]
}

func (x CheckpointState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointState.Descriptor instead.
func (CheckpointState) EnumDescriptor() ([]byte, []int) {
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

type CheckpointStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state of the current checkpointing process.
	State CheckpointState `protobuf:"varint,1,opt,name=state,proto3,enum=platformd.checkpoint.v1alpha1.CheckpointState" json:"state,omitempty"`
	// message provides details as to why the checkpoint is
	// in this state. this field is optional.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointStatus) Reset() {
	*x = CheckpointStatus{}
	mi := &file_platformd_checkpoint_v1alpha1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointStatus) ProtoMessage() {}

func (x *CheckpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_checkpoint_v1alpha1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointStatus.ProtoReflect.Descriptor instead.
func (*CheckpointStatus) Descriptor() ([]byte, []int) {
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointStatus) GetState() CheckpointState {
	if x != nil {
		return x.State
	}
	return CheckpointState_RUNNING
}

func (x *CheckpointStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_platformd_checkpoint_v1alpha1_types_proto protoreflect.FileDescriptor

const file_platformd_checkpoint_v1alpha1_types_proto_rawDesc = "" +
	"\n" +
	")platformd/checkpoint/v1alpha1/types.proto\x12\x1dplatformd.checkpoint.v1alpha1\"r\n" +
	"\x10CheckpointStatus\x12D\n" +
	"\x05state\x18\x01 \x01(\x0e2..platformd.checkpoint.v1alpha1.CheckpointStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xa7\x01\n" +
	"\x0fCheckpointState\x12\v\n" +
	"\aRUNNING\x10\x00\x12\x1a\n" +
	"\x16PULL_BASE_IMAGE_FAILED\x10\x01\x12\x1f\n" +
	"\x1bCONTAINER_WAIT_READY_FAILED\x10\x02\x12\x1f\n" +
	"\x1bCONTAINER_CHECKPOINT_FAILED\x10\x03\x12\x1a\n" +
	"\x16PUSH_CHECKPOINT_FAILED\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05BCZAgithub.com/spacechunks/explorer/api/platformd/checkpoint/v1alpha1b\x06proto3"

var (
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescOnce sync.Once
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescData []byte
)

func file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP() []byte {
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescOnce.Do(func() {
		file_platformd_checkpoint_v1alpha1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformd_checkpoint_v1alpha1_types_proto_rawDesc), len(file_platformd_checkpoint_v1alpha1_types_proto_rawDesc)))
	})
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescData
}

var file_platformd_checkpoint_v1alpha1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platformd_checkpoint_v1alpha1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_platformd_checkpoint_v1alpha1_types_proto_goTypes = []any{
	(CheckpointState)(0),     // 0: platformd.checkpoint.v1alpha1.CheckpointState
	(*CheckpointStatus)(nil), // 1: platformd.checkpoint.v1alpha1.CheckpointStatus
}
var file_platformd_checkpoint_v1alpha1_types_proto_depIdxs = []int32{
	0, // 0: platformd.checkpoint.v1alpha1.CheckpointStatus.state:type_name -> platformd.checkpoint.v1alpha1.CheckpointState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platformd_checkpoint_v1alpha1_types_proto_init() }
func file_platformd_checkpoint_v1alpha1_types_proto_init() {
	if File_platformd_checkpoint_v1alpha1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformd_checkpoint_v1alpha1_types_proto_rawDesc), len(file_platformd_checkpoint_v1alpha1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platformd_checkpoint_v1alpha1_types_proto_goTypes,
		DependencyIndexes: file_platformd_checkpoint_v1alpha1_types_proto_depIdxs,
		EnumInfos:         file_platformd_checkpoint_v1alpha1_types_proto_enumTypes,
		MessageInfos:      file_platformd_checkpoint_v1alpha1_types_proto_msgTypes,
	}.Build()
	File_platformd_checkpoint_v1alpha1_types_proto = out.File
	file_platformd_checkpoint_v1alpha1_types_proto_goTypes = nil
	file_platformd_checkpoint_v1alpha1_types_proto_depIdxs = nil
}
