//
//Chunk Explorer, a platform for hosting and discovering Minecraft servers.
//Copyright (C) 2025 Yannic Rieger <oss@76k.io>
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU Lesser General Public
//License as published by the Free Software Foundation; either
//version 3 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//Lesser General Public License for more details.
//
//You should have received a copy of the GNU Lesser General Public License
//along with this program; if not, write to the Free Software Foundation,
//Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platformd/workload/v1alpha2/types.proto

package v1alpha2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadState int32

const (
	WorkloadState_UNKNOWN         WorkloadState = 0
	WorkloadState_STARTING        WorkloadState = 1
	WorkloadState_RUNNING         WorkloadState = 2
	WorkloadState_DELETING        WorkloadState = 3
	WorkloadState_DELETED         WorkloadState = 4
	WorkloadState_CREATION_FAILED WorkloadState = 5
)

// Enum value maps for WorkloadState.
var (
	WorkloadState_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTING",
		2: "RUNNING",
		3: "DELETING",
		4: "DELETED",
		5: "CREATION_FAILED",
	}
	WorkloadState_value = map[string]int32{
		"UNKNOWN":         0,
		"STARTING":        1,
		"RUNNING":         2,
		"DELETING":        3,
		"DELETED":         4,
		"CREATION_FAILED": 5,
	}
)

func (x WorkloadState) Enum() *WorkloadState {
	p := new(WorkloadState)
	*p = x
	return p
}

func (x WorkloadState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadState) Descriptor() protoreflect.EnumDescriptor {
	return file_platformd_workload_v1alpha2_types_proto_enumTypes[0].Descriptor()
}

func (WorkloadState) Type() protoreflect.EnumType {
	return &file_platformd_workload_v1alpha2_types_proto_enumTypes[0]
}

func (x WorkloadState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadState.Descriptor instead.
func (WorkloadState) EnumDescriptor() ([]byte, []int) {
	return file_platformd_workload_v1alpha2_types_proto_rawDescGZIP(), []int{0}
}

type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a universally unique value identifying the workload.
	// currently this is in UUIDv7 format.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name of the workload.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// base_image_url points to the image that was used to create the checkpoint
	// provided by checkpoint_image_url.
	BaseImageUrl string `protobuf:"bytes,3,opt,name=base_image_url,json=baseImageUrl,proto3" json:"base_image_url,omitempty"`
	// checkpoint_image_url points to a checkpoint living in an oci compatible
	// registry.
	CheckpointImageUrl string `protobuf:"bytes,4,opt,name=checkpoint_image_url,json=checkpointImageUrl,proto3" json:"checkpoint_image_url,omitempty"`
	// namespace the workload is be created in.
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// hostname of the pod.
	Hostname string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// labels applied to the pod.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// the network namespace' mode as per [runtimev1.NamespaceMode].
	NetworkNamespaceMode int32 `protobuf:"varint,8,opt,name=network_namespace_mode,json=networkNamespaceMode,proto3" json:"network_namespace_mode,omitempty"`
	// status
	State         WorkloadState `protobuf:"varint,9,opt,name=state,proto3,enum=platformd.workload.v1alpha2.WorkloadState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_platformd_workload_v1alpha2_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_workload_v1alpha2_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_platformd_workload_v1alpha2_types_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetBaseImageUrl() string {
	if x != nil {
		return x.BaseImageUrl
	}
	return ""
}

func (x *Workload) GetCheckpointImageUrl() string {
	if x != nil {
		return x.CheckpointImageUrl
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Workload) GetNetworkNamespaceMode() int32 {
	if x != nil {
		return x.NetworkNamespaceMode
	}
	return 0
}

func (x *Workload) GetState() WorkloadState {
	if x != nil {
		return x.State
	}
	return WorkloadState_UNKNOWN
}

type WorkloadStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State WorkloadState          `protobuf:"varint,2,opt,name=state,proto3,enum=platformd.workload.v1alpha2.WorkloadState" json:"state,omitempty"`
	// port allocated for the workload. programs binding
	// to this port will be reachable from the internet.
	Port          uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_platformd_workload_v1alpha2_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_workload_v1alpha2_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_platformd_workload_v1alpha2_types_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadStatus) GetState() WorkloadState {
	if x != nil {
		return x.State
	}
	return WorkloadState_UNKNOWN
}

func (x *WorkloadStatus) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_platformd_workload_v1alpha2_types_proto protoreflect.FileDescriptor

const file_platformd_workload_v1alpha2_types_proto_rawDesc = "" +
	"\n" +
	"'platformd/workload/v1alpha2/types.proto\x12\x1bplatformd.workload.v1alpha2\"\xbe\x03\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0ebase_image_url\x18\x03 \x01(\tR\fbaseImageUrl\x120\n" +
	"\x14checkpoint_image_url\x18\x04 \x01(\tR\x12checkpointImageUrl\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12I\n" +
	"\x06labels\x18\a \x03(\v21.platformd.workload.v1alpha2.Workload.LabelsEntryR\x06labels\x124\n" +
	"\x16network_namespace_mode\x18\b \x01(\x05R\x14networkNamespaceMode\x12@\n" +
	"\x05state\x18\t \x01(\x0e2*.platformd.workload.v1alpha2.WorkloadStateR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x0eWorkloadStatus\x12@\n" +
	"\x05state\x18\x02 \x01(\x0e2*.platformd.workload.v1alpha2.WorkloadStateR\x05state\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port*g\n" +
	"\rWorkloadState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bDELETING\x10\x03\x12\v\n" +
	"\aDELETED\x10\x04\x12\x13\n" +
	"\x0fCREATION_FAILED\x10\x05BAZ?github.com/spacechunks/explorer/api/platformd/workload/v1alpha2b\x06proto3"

var (
	file_platformd_workload_v1alpha2_types_proto_rawDescOnce sync.Once
	file_platformd_workload_v1alpha2_types_proto_rawDescData []byte
)

func file_platformd_workload_v1alpha2_types_proto_rawDescGZIP() []byte {
	file_platformd_workload_v1alpha2_types_proto_rawDescOnce.Do(func() {
		file_platformd_workload_v1alpha2_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformd_workload_v1alpha2_types_proto_rawDesc), len(file_platformd_workload_v1alpha2_types_proto_rawDesc)))
	})
	return file_platformd_workload_v1alpha2_types_proto_rawDescData
}

var file_platformd_workload_v1alpha2_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platformd_workload_v1alpha2_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platformd_workload_v1alpha2_types_proto_goTypes = []any{
	(WorkloadState)(0),     // 0: platformd.workload.v1alpha2.WorkloadState
	(*Workload)(nil),       // 1: platformd.workload.v1alpha2.Workload
	(*WorkloadStatus)(nil), // 2: platformd.workload.v1alpha2.WorkloadStatus
	nil,                    // 3: platformd.workload.v1alpha2.Workload.LabelsEntry
}
var file_platformd_workload_v1alpha2_types_proto_depIdxs = []int32{
	3, // 0: platformd.workload.v1alpha2.Workload.labels:type_name -> platformd.workload.v1alpha2.Workload.LabelsEntry
	0, // 1: platformd.workload.v1alpha2.Workload.state:type_name -> platformd.workload.v1alpha2.WorkloadState
	0, // 2: platformd.workload.v1alpha2.WorkloadStatus.state:type_name -> platformd.workload.v1alpha2.WorkloadState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_platformd_workload_v1alpha2_types_proto_init() }
func file_platformd_workload_v1alpha2_types_proto_init() {
	if File_platformd_workload_v1alpha2_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformd_workload_v1alpha2_types_proto_rawDesc), len(file_platformd_workload_v1alpha2_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platformd_workload_v1alpha2_types_proto_goTypes,
		DependencyIndexes: file_platformd_workload_v1alpha2_types_proto_depIdxs,
		EnumInfos:         file_platformd_workload_v1alpha2_types_proto_enumTypes,
		MessageInfos:      file_platformd_workload_v1alpha2_types_proto_msgTypes,
	}.Build()
	File_platformd_workload_v1alpha2_types_proto = out.File
	file_platformd_workload_v1alpha2_types_proto_goTypes = nil
	file_platformd_workload_v1alpha2_types_proto_depIdxs = nil
}
