with-expecter: true
disable-version-string: true
dir: internal/mock
outpkg: mock
filename: "{{ .PackageName }}_{{ .InterfaceName | snakecase }}.go"
mockname: "Mock{{ .PackageName | camelcase }}{{ .InterfaceName }}"
packages:
  github.com/spacechunks/platform/internal/ptpnat:
    interfaces:
      Handler:
  github.com/envoyproxy/go-control-plane/pkg/cache/v3:
    interfaces:
      SnapshotCache:
