with-expecter: true
disable-version-string: true
dir: internal/mock
outpkg: mock
filename: "{{ .PackageName }}_{{ .InterfaceName | snakecase }}.go"
mockname: "Mock{{ .PackageName | camelcase }}{{ .InterfaceName }}"
packages:
  github.com/spacechunks/explorer/controlplane/blob:
    interfaces:
      Store:
      Repository:
  github.com/spacechunks/explorer/platformd/proxy/xds:
    interfaces:
      Map:
  github.com/spacechunks/explorer/cni:
    interfaces:
      Handler:
  github.com/spacechunks/explorer/platformd/cri:
    interfaces:
      Service:
  github.com/spacechunks/explorer/platformd/workload:
    interfaces:
      Service:
      StatusStore:
  github.com/spacechunks/explorer/controlplane/chunk:
    interfaces:
      Repository:
  github.com/spacechunks/explorer/api/instance/v1alpha1:
    interfaces:
      InstanceServiceClient:
  github.com/spacechunks/explorer/api/platformd/proxy/v1alpha1:
    interfaces:
      ProxyServiceClient:
  github.com/spacechunks/explorer/api/platformd/workload/v1alpha2:
    interfaces:
      WorkloadServiceClient:
  k8s.io/cri-api/pkg/apis/runtime/v1:
    interfaces:
      RuntimeServiceClient:
      ImageServiceClient:
  github.com/envoyproxy/go-control-plane/pkg/cache/v3:
    interfaces:
      SnapshotCache:
