---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-ingress-cert
spec:
  # Secret names are always required.
  secretName: harbor-ingress-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - chunks
  commonName: reg1.chunks.76k.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - reg1.chunks.76k.io
  issuerRef:
    name: letsencrypt-acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io