---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- harbor.helmrelease.yaml
- harbor.helmrepository.yaml
- ingress.certificate.yaml
- harbor-token.certificate.yaml
- ns.yaml
