apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chunker
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - services
      - deployments
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
