apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-token-cert
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: harbor-token-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - token.reg1.chunks.76k.io
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io