apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wlc
spec:
  dependsOn:
    - name: cert-manager-issuer
  interval: 5s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: chunks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5s
  path: ./cert-manager/issuer
  prune: true
  sourceRef:
    kind: OCIRepository
    name: chunks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5s
  path: ./cert-manager
  prune: true
  sourceRef:
    kind: OCIRepository
    name: chunks