// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BuildStatus string

const (
	BuildStatusPENDING               BuildStatus = "PENDING"
	BuildStatusIMAGEBUILD            BuildStatus = "IMAGE_BUILD"
	BuildStatusIMAGEBUILDFAILED      BuildStatus = "IMAGE_BUILD_FAILED"
	BuildStatusCHECKPOINTBUILD       BuildStatus = "CHECKPOINT_BUILD"
	BuildStatusCHECKPOINTBUILDFAILED BuildStatus = "CHECKPOINT_BUILD_FAILED"
	BuildStatusCOMPLETED             BuildStatus = "COMPLETED"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus
	Valid       bool // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

type InstanceState string

const (
	InstanceStatePENDING        InstanceState = "PENDING"
	InstanceStateCREATING       InstanceState = "CREATING"
	InstanceStateRUNNING        InstanceState = "RUNNING"
	InstanceStateDELETING       InstanceState = "DELETING"
	InstanceStateDELETED        InstanceState = "DELETED"
	InstanceStateCREATIONFAILED InstanceState = "CREATION_FAILED"
)

func (e *InstanceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceState(s)
	case string:
		*e = InstanceState(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceState: %T", src)
	}
	return nil
}

type NullInstanceState struct {
	InstanceState InstanceState
	Valid         bool // Valid is true if InstanceState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceState) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceState), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Blob struct {
	Hash      string
	Data      []byte
	CreatedAt time.Time
}

type Chunk struct {
	ID                 string
	Name               string
	Description        string
	Tags               []string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	OwnerID            string
	ThumbnailHash      pgtype.Text
	ThumbnailUpdatedAt time.Time
}

type Flavor struct {
	ID        string
	ChunkID   string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FlavorVersion struct {
	ID                     string
	FlavorID               string
	Hash                   string
	ChangeHash             string
	BuildStatus            BuildStatus
	Version                string
	FilesUploaded          bool
	PrevVersionID          *string
	CreatedAt              time.Time
	PresignedUrlExpiryDate pgtype.Timestamptz
	PresignedUrl           pgtype.Text
	MinecraftVersion       string
}

type FlavorVersionFile struct {
	FlavorVersionID string
	FileHash        string
	FilePath        string
	CreatedAt       time.Time
}

type Instance struct {
	ID              string
	ChunkID         string
	FlavorVersionID string
	NodeID          string
	Port            *int32
	State           InstanceState
	CreatedAt       time.Time
	UpdatedAt       time.Time
	OwnerID         string
}

type MinecraftVersion struct {
	Version   string
	CreatedAt pgtype.Timestamptz
}

type Node struct {
	ID                    string
	Name                  string
	Address               netip.Addr
	CheckpointApiEndpoint string
	CreatedAt             time.Time
}

type RiverClient struct {
	ID        string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt time.Time
}

type RiverClientQueue struct {
	RiverClientID    string
	Name             string
	CreatedAt        time.Time
	MaxWorkers       int64
	Metadata         []byte
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    time.Time
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID        string
	Nickname  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
