---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.35.3
      sourceRef:
        kind: HelmRepository
        name: haproxy-tech
        namespace: ingress
      interval: 1m
  values:
    controller:
      kind: DaemonSet
      containerPort:
        http: 8080
        https: 8443
        stat: 1024
      resources:
        requests:
          cpu: 250m
          memory: 400Mi
      # ref: https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation
      config: {}
      #   timeout-connect: "250ms"
      #   servers-increment: "10"
      #   servers-increment-max-disabled: "10"
      #   rate-limit: "ON"
      #   rate-limit-expire: "1m"
      #   rate-limit-interval: "10s"
      #   rate-limit-size: "100k"
      logging:
        # controller logs only
        level: debug
        # ref: https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#logging
        traffic:
          address:  "stdout"
          format:   "raw"
          facility: "daemon"
      service:
        enabled: true   
        type: NodePort
        ports:
          http: 80
          https: 443
          stat: 1024
          prometheus: 6060
        nodePorts:
          http: 30080
          https: 30443
        enablePorts:
          http: true
          https: true
          stat: true
          prometheus: true
