// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"
	io "io"
	time "time"

	blob "github.com/spacechunks/explorer/controlplane/blob"
	mock "github.com/stretchr/testify/mock"
)

// MockBlobS3Store is an autogenerated mock type for the S3Store type
type MockBlobS3Store struct {
	mock.Mock
}

type MockBlobS3Store_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobS3Store) EXPECT() *MockBlobS3Store_Expecter {
	return &MockBlobS3Store_Expecter{mock: &_m.Mock}
}

// ObjectExists provides a mock function with given fields: ctx, key
func (_m *MockBlobS3Store) ObjectExists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ObjectExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlobS3Store_ObjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectExists'
type MockBlobS3Store_ObjectExists_Call struct {
	*mock.Call
}

// ObjectExists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockBlobS3Store_Expecter) ObjectExists(ctx interface{}, key interface{}) *MockBlobS3Store_ObjectExists_Call {
	return &MockBlobS3Store_ObjectExists_Call{Call: _e.mock.On("ObjectExists", ctx, key)}
}

func (_c *MockBlobS3Store_ObjectExists_Call) Run(run func(ctx context.Context, key string)) *MockBlobS3Store_ObjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBlobS3Store_ObjectExists_Call) Return(_a0 bool, _a1 error) *MockBlobS3Store_ObjectExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlobS3Store_ObjectExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockBlobS3Store_ObjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// PresignURL provides a mock function with given fields: ctx, key, contentHash, expiry
func (_m *MockBlobS3Store) PresignURL(ctx context.Context, key string, contentHash string, expiry time.Duration) (string, time.Time, error) {
	ret := _m.Called(ctx, key, contentHash, expiry)

	if len(ret) == 0 {
		panic("no return value specified for PresignURL")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, time.Time, error)); ok {
		return rf(ctx, key, contentHash, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = rf(ctx, key, contentHash, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) time.Time); ok {
		r1 = rf(ctx, key, contentHash, expiry)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, time.Duration) error); ok {
		r2 = rf(ctx, key, contentHash, expiry)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBlobS3Store_PresignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignURL'
type MockBlobS3Store_PresignURL_Call struct {
	*mock.Call
}

// PresignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentHash string
//   - expiry time.Duration
func (_e *MockBlobS3Store_Expecter) PresignURL(ctx interface{}, key interface{}, contentHash interface{}, expiry interface{}) *MockBlobS3Store_PresignURL_Call {
	return &MockBlobS3Store_PresignURL_Call{Call: _e.mock.On("PresignURL", ctx, key, contentHash, expiry)}
}

func (_c *MockBlobS3Store_PresignURL_Call) Run(run func(ctx context.Context, key string, contentHash string, expiry time.Duration)) *MockBlobS3Store_PresignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockBlobS3Store_PresignURL_Call) Return(_a0 string, _a1 time.Time, _a2 error) *MockBlobS3Store_PresignURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBlobS3Store_PresignURL_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (string, time.Time, error)) *MockBlobS3Store_PresignURL_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, keyPrefix, objects
func (_m *MockBlobS3Store) Put(ctx context.Context, keyPrefix string, objects []blob.Object) error {
	ret := _m.Called(ctx, keyPrefix, objects)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []blob.Object) error); ok {
		r0 = rf(ctx, keyPrefix, objects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobS3Store_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBlobS3Store_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - keyPrefix string
//   - objects []blob.Object
func (_e *MockBlobS3Store_Expecter) Put(ctx interface{}, keyPrefix interface{}, objects interface{}) *MockBlobS3Store_Put_Call {
	return &MockBlobS3Store_Put_Call{Call: _e.mock.On("Put", ctx, keyPrefix, objects)}
}

func (_c *MockBlobS3Store_Put_Call) Run(run func(ctx context.Context, keyPrefix string, objects []blob.Object)) *MockBlobS3Store_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]blob.Object))
	})
	return _c
}

func (_c *MockBlobS3Store_Put_Call) Return(_a0 error) *MockBlobS3Store_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobS3Store_Put_Call) RunAndReturn(run func(context.Context, string, []blob.Object) error) *MockBlobS3Store_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SimplePut provides a mock function with given fields: ctx, key, r, metadata
func (_m *MockBlobS3Store) SimplePut(ctx context.Context, key string, r io.Reader, metadata map[string]string) error {
	ret := _m.Called(ctx, key, r, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SimplePut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, map[string]string) error); ok {
		r0 = rf(ctx, key, r, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobS3Store_SimplePut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimplePut'
type MockBlobS3Store_SimplePut_Call struct {
	*mock.Call
}

// SimplePut is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - metadata map[string]string
func (_e *MockBlobS3Store_Expecter) SimplePut(ctx interface{}, key interface{}, r interface{}, metadata interface{}) *MockBlobS3Store_SimplePut_Call {
	return &MockBlobS3Store_SimplePut_Call{Call: _e.mock.On("SimplePut", ctx, key, r, metadata)}
}

func (_c *MockBlobS3Store_SimplePut_Call) Run(run func(ctx context.Context, key string, r io.Reader, metadata map[string]string)) *MockBlobS3Store_SimplePut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockBlobS3Store_SimplePut_Call) Return(_a0 error) *MockBlobS3Store_SimplePut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobS3Store_SimplePut_Call) RunAndReturn(run func(context.Context, string, io.Reader, map[string]string) error) *MockBlobS3Store_SimplePut_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTo provides a mock function with given fields: ctx, key, w
func (_m *MockBlobS3Store) WriteTo(ctx context.Context, key string, w io.Writer) error {
	ret := _m.Called(ctx, key, w)

	if len(ret) == 0 {
		panic("no return value specified for WriteTo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Writer) error); ok {
		r0 = rf(ctx, key, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlobS3Store_WriteTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTo'
type MockBlobS3Store_WriteTo_Call struct {
	*mock.Call
}

// WriteTo is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - w io.Writer
func (_e *MockBlobS3Store_Expecter) WriteTo(ctx interface{}, key interface{}, w interface{}) *MockBlobS3Store_WriteTo_Call {
	return &MockBlobS3Store_WriteTo_Call{Call: _e.mock.On("WriteTo", ctx, key, w)}
}

func (_c *MockBlobS3Store_WriteTo_Call) Run(run func(ctx context.Context, key string, w io.Writer)) *MockBlobS3Store_WriteTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Writer))
	})
	return _c
}

func (_c *MockBlobS3Store_WriteTo_Call) Return(_a0 error) *MockBlobS3Store_WriteTo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlobS3Store_WriteTo_Call) RunAndReturn(run func(context.Context, string, io.Writer) error) *MockBlobS3Store_WriteTo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlobS3Store creates a new instance of MockBlobS3Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobS3Store(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobS3Store {
	mock := &MockBlobS3Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
