// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	cache "github.com/envoyproxy/go-control-plane/pkg/cache/v3"

	discoveryv3 "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"

	mock "github.com/stretchr/testify/mock"
)

// MockcacheSnapshotCache is an autogenerated mock type for the SnapshotCache type
type MockcacheSnapshotCache struct {
	mock.Mock
}

type MockcacheSnapshotCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcacheSnapshotCache) EXPECT() *MockcacheSnapshotCache_Expecter {
	return &MockcacheSnapshotCache_Expecter{mock: &_m.Mock}
}

// ClearSnapshot provides a mock function with given fields: node
func (_m *MockcacheSnapshotCache) ClearSnapshot(node string) {
	_m.Called(node)
}

// MockcacheSnapshotCache_ClearSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSnapshot'
type MockcacheSnapshotCache_ClearSnapshot_Call struct {
	*mock.Call
}

// ClearSnapshot is a helper method to define mock.On call
//   - node string
func (_e *MockcacheSnapshotCache_Expecter) ClearSnapshot(node interface{}) *MockcacheSnapshotCache_ClearSnapshot_Call {
	return &MockcacheSnapshotCache_ClearSnapshot_Call{Call: _e.mock.On("ClearSnapshot", node)}
}

func (_c *MockcacheSnapshotCache_ClearSnapshot_Call) Run(run func(node string)) *MockcacheSnapshotCache_ClearSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_ClearSnapshot_Call) Return() *MockcacheSnapshotCache_ClearSnapshot_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockcacheSnapshotCache_ClearSnapshot_Call) RunAndReturn(run func(string)) *MockcacheSnapshotCache_ClearSnapshot_Call {
	_c.Run(run)
	return _c
}

// CreateDeltaWatch provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockcacheSnapshotCache) CreateDeltaWatch(_a0 *discoveryv3.DeltaDiscoveryRequest, _a1 cache.Subscription, _a2 chan cache.DeltaResponse) (func(), error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeltaWatch")
	}

	var r0 func()
	var r1 error
	if rf, ok := ret.Get(0).(func(*discoveryv3.DeltaDiscoveryRequest, cache.Subscription, chan cache.DeltaResponse) (func(), error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(*discoveryv3.DeltaDiscoveryRequest, cache.Subscription, chan cache.DeltaResponse) func()); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(*discoveryv3.DeltaDiscoveryRequest, cache.Subscription, chan cache.DeltaResponse) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcacheSnapshotCache_CreateDeltaWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeltaWatch'
type MockcacheSnapshotCache_CreateDeltaWatch_Call struct {
	*mock.Call
}

// CreateDeltaWatch is a helper method to define mock.On call
//   - _a0 *discoveryv3.DeltaDiscoveryRequest
//   - _a1 cache.Subscription
//   - _a2 chan cache.DeltaResponse
func (_e *MockcacheSnapshotCache_Expecter) CreateDeltaWatch(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockcacheSnapshotCache_CreateDeltaWatch_Call {
	return &MockcacheSnapshotCache_CreateDeltaWatch_Call{Call: _e.mock.On("CreateDeltaWatch", _a0, _a1, _a2)}
}

func (_c *MockcacheSnapshotCache_CreateDeltaWatch_Call) Run(run func(_a0 *discoveryv3.DeltaDiscoveryRequest, _a1 cache.Subscription, _a2 chan cache.DeltaResponse)) *MockcacheSnapshotCache_CreateDeltaWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*discoveryv3.DeltaDiscoveryRequest), args[1].(cache.Subscription), args[2].(chan cache.DeltaResponse))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_CreateDeltaWatch_Call) Return(cancel func(), err error) *MockcacheSnapshotCache_CreateDeltaWatch_Call {
	_c.Call.Return(cancel, err)
	return _c
}

func (_c *MockcacheSnapshotCache_CreateDeltaWatch_Call) RunAndReturn(run func(*discoveryv3.DeltaDiscoveryRequest, cache.Subscription, chan cache.DeltaResponse) (func(), error)) *MockcacheSnapshotCache_CreateDeltaWatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWatch provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockcacheSnapshotCache) CreateWatch(_a0 *discoveryv3.DiscoveryRequest, _a1 cache.Subscription, _a2 chan cache.Response) (func(), error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateWatch")
	}

	var r0 func()
	var r1 error
	if rf, ok := ret.Get(0).(func(*discoveryv3.DiscoveryRequest, cache.Subscription, chan cache.Response) (func(), error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(*discoveryv3.DiscoveryRequest, cache.Subscription, chan cache.Response) func()); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	if rf, ok := ret.Get(1).(func(*discoveryv3.DiscoveryRequest, cache.Subscription, chan cache.Response) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcacheSnapshotCache_CreateWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWatch'
type MockcacheSnapshotCache_CreateWatch_Call struct {
	*mock.Call
}

// CreateWatch is a helper method to define mock.On call
//   - _a0 *discoveryv3.DiscoveryRequest
//   - _a1 cache.Subscription
//   - _a2 chan cache.Response
func (_e *MockcacheSnapshotCache_Expecter) CreateWatch(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockcacheSnapshotCache_CreateWatch_Call {
	return &MockcacheSnapshotCache_CreateWatch_Call{Call: _e.mock.On("CreateWatch", _a0, _a1, _a2)}
}

func (_c *MockcacheSnapshotCache_CreateWatch_Call) Run(run func(_a0 *discoveryv3.DiscoveryRequest, _a1 cache.Subscription, _a2 chan cache.Response)) *MockcacheSnapshotCache_CreateWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*discoveryv3.DiscoveryRequest), args[1].(cache.Subscription), args[2].(chan cache.Response))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_CreateWatch_Call) Return(cancel func(), err error) *MockcacheSnapshotCache_CreateWatch_Call {
	_c.Call.Return(cancel, err)
	return _c
}

func (_c *MockcacheSnapshotCache_CreateWatch_Call) RunAndReturn(run func(*discoveryv3.DiscoveryRequest, cache.Subscription, chan cache.Response) (func(), error)) *MockcacheSnapshotCache_CreateWatch_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: _a0, _a1
func (_m *MockcacheSnapshotCache) Fetch(_a0 context.Context, _a1 *discoveryv3.DiscoveryRequest) (cache.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 cache.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *discoveryv3.DiscoveryRequest) (cache.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *discoveryv3.DiscoveryRequest) cache.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *discoveryv3.DiscoveryRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcacheSnapshotCache_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockcacheSnapshotCache_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *discoveryv3.DiscoveryRequest
func (_e *MockcacheSnapshotCache_Expecter) Fetch(_a0 interface{}, _a1 interface{}) *MockcacheSnapshotCache_Fetch_Call {
	return &MockcacheSnapshotCache_Fetch_Call{Call: _e.mock.On("Fetch", _a0, _a1)}
}

func (_c *MockcacheSnapshotCache_Fetch_Call) Run(run func(_a0 context.Context, _a1 *discoveryv3.DiscoveryRequest)) *MockcacheSnapshotCache_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*discoveryv3.DiscoveryRequest))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_Fetch_Call) Return(_a0 cache.Response, _a1 error) *MockcacheSnapshotCache_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcacheSnapshotCache_Fetch_Call) RunAndReturn(run func(context.Context, *discoveryv3.DiscoveryRequest) (cache.Response, error)) *MockcacheSnapshotCache_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshot provides a mock function with given fields: node
func (_m *MockcacheSnapshotCache) GetSnapshot(node string) (cache.ResourceSnapshot, error) {
	ret := _m.Called(node)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 cache.ResourceSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (cache.ResourceSnapshot, error)); ok {
		return rf(node)
	}
	if rf, ok := ret.Get(0).(func(string) cache.ResourceSnapshot); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.ResourceSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(node)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcacheSnapshotCache_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type MockcacheSnapshotCache_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - node string
func (_e *MockcacheSnapshotCache_Expecter) GetSnapshot(node interface{}) *MockcacheSnapshotCache_GetSnapshot_Call {
	return &MockcacheSnapshotCache_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot", node)}
}

func (_c *MockcacheSnapshotCache_GetSnapshot_Call) Run(run func(node string)) *MockcacheSnapshotCache_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_GetSnapshot_Call) Return(_a0 cache.ResourceSnapshot, _a1 error) *MockcacheSnapshotCache_GetSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcacheSnapshotCache_GetSnapshot_Call) RunAndReturn(run func(string) (cache.ResourceSnapshot, error)) *MockcacheSnapshotCache_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusInfo provides a mock function with given fields: _a0
func (_m *MockcacheSnapshotCache) GetStatusInfo(_a0 string) cache.StatusInfo {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusInfo")
	}

	var r0 cache.StatusInfo
	if rf, ok := ret.Get(0).(func(string) cache.StatusInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.StatusInfo)
		}
	}

	return r0
}

// MockcacheSnapshotCache_GetStatusInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusInfo'
type MockcacheSnapshotCache_GetStatusInfo_Call struct {
	*mock.Call
}

// GetStatusInfo is a helper method to define mock.On call
//   - _a0 string
func (_e *MockcacheSnapshotCache_Expecter) GetStatusInfo(_a0 interface{}) *MockcacheSnapshotCache_GetStatusInfo_Call {
	return &MockcacheSnapshotCache_GetStatusInfo_Call{Call: _e.mock.On("GetStatusInfo", _a0)}
}

func (_c *MockcacheSnapshotCache_GetStatusInfo_Call) Run(run func(_a0 string)) *MockcacheSnapshotCache_GetStatusInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_GetStatusInfo_Call) Return(_a0 cache.StatusInfo) *MockcacheSnapshotCache_GetStatusInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcacheSnapshotCache_GetStatusInfo_Call) RunAndReturn(run func(string) cache.StatusInfo) *MockcacheSnapshotCache_GetStatusInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusKeys provides a mock function with no fields
func (_m *MockcacheSnapshotCache) GetStatusKeys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatusKeys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockcacheSnapshotCache_GetStatusKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusKeys'
type MockcacheSnapshotCache_GetStatusKeys_Call struct {
	*mock.Call
}

// GetStatusKeys is a helper method to define mock.On call
func (_e *MockcacheSnapshotCache_Expecter) GetStatusKeys() *MockcacheSnapshotCache_GetStatusKeys_Call {
	return &MockcacheSnapshotCache_GetStatusKeys_Call{Call: _e.mock.On("GetStatusKeys")}
}

func (_c *MockcacheSnapshotCache_GetStatusKeys_Call) Run(run func()) *MockcacheSnapshotCache_GetStatusKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockcacheSnapshotCache_GetStatusKeys_Call) Return(_a0 []string) *MockcacheSnapshotCache_GetStatusKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcacheSnapshotCache_GetStatusKeys_Call) RunAndReturn(run func() []string) *MockcacheSnapshotCache_GetStatusKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SetSnapshot provides a mock function with given fields: ctx, node, snapshot
func (_m *MockcacheSnapshotCache) SetSnapshot(ctx context.Context, node string, snapshot cache.ResourceSnapshot) error {
	ret := _m.Called(ctx, node, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for SetSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, cache.ResourceSnapshot) error); ok {
		r0 = rf(ctx, node, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockcacheSnapshotCache_SetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSnapshot'
type MockcacheSnapshotCache_SetSnapshot_Call struct {
	*mock.Call
}

// SetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - node string
//   - snapshot cache.ResourceSnapshot
func (_e *MockcacheSnapshotCache_Expecter) SetSnapshot(ctx interface{}, node interface{}, snapshot interface{}) *MockcacheSnapshotCache_SetSnapshot_Call {
	return &MockcacheSnapshotCache_SetSnapshot_Call{Call: _e.mock.On("SetSnapshot", ctx, node, snapshot)}
}

func (_c *MockcacheSnapshotCache_SetSnapshot_Call) Run(run func(ctx context.Context, node string, snapshot cache.ResourceSnapshot)) *MockcacheSnapshotCache_SetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(cache.ResourceSnapshot))
	})
	return _c
}

func (_c *MockcacheSnapshotCache_SetSnapshot_Call) Return(_a0 error) *MockcacheSnapshotCache_SetSnapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcacheSnapshotCache_SetSnapshot_Call) RunAndReturn(run func(context.Context, string, cache.ResourceSnapshot) error) *MockcacheSnapshotCache_SetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcacheSnapshotCache creates a new instance of MockcacheSnapshotCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcacheSnapshotCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcacheSnapshotCache {
	mock := &MockcacheSnapshotCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
