// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	resource "github.com/spacechunks/explorer/controlplane/resource"
	mock "github.com/stretchr/testify/mock"
)

// MockChunkArchiveRepository is an autogenerated mock type for the ArchiveRepository type
type MockChunkArchiveRepository struct {
	mock.Mock
}

type MockChunkArchiveRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunkArchiveRepository) EXPECT() *MockChunkArchiveRepository_Expecter {
	return &MockChunkArchiveRepository_Expecter{mock: &_m.Mock}
}

// ArchiveChunk provides a mock function with given fields: ctx, _a1
func (_m *MockChunkArchiveRepository) ArchiveChunk(ctx context.Context, _a1 resource.Chunk) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, resource.Chunk) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunkArchiveRepository_ArchiveChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveChunk'
type MockChunkArchiveRepository_ArchiveChunk_Call struct {
	*mock.Call
}

// ArchiveChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 resource.Chunk
func (_e *MockChunkArchiveRepository_Expecter) ArchiveChunk(ctx interface{}, _a1 interface{}) *MockChunkArchiveRepository_ArchiveChunk_Call {
	return &MockChunkArchiveRepository_ArchiveChunk_Call{Call: _e.mock.On("ArchiveChunk", ctx, _a1)}
}

func (_c *MockChunkArchiveRepository_ArchiveChunk_Call) Run(run func(ctx context.Context, _a1 resource.Chunk)) *MockChunkArchiveRepository_ArchiveChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(resource.Chunk))
	})
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveChunk_Call) Return(_a0 error) *MockChunkArchiveRepository_ArchiveChunk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveChunk_Call) RunAndReturn(run func(context.Context, resource.Chunk) error) *MockChunkArchiveRepository_ArchiveChunk_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveFlavor provides a mock function with given fields: ctx, chunkID, flavor
func (_m *MockChunkArchiveRepository) ArchiveFlavor(ctx context.Context, chunkID string, flavor resource.Flavor) error {
	ret := _m.Called(ctx, chunkID, flavor)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveFlavor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, resource.Flavor) error); ok {
		r0 = rf(ctx, chunkID, flavor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunkArchiveRepository_ArchiveFlavor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveFlavor'
type MockChunkArchiveRepository_ArchiveFlavor_Call struct {
	*mock.Call
}

// ArchiveFlavor is a helper method to define mock.On call
//   - ctx context.Context
//   - chunkID string
//   - flavor resource.Flavor
func (_e *MockChunkArchiveRepository_Expecter) ArchiveFlavor(ctx interface{}, chunkID interface{}, flavor interface{}) *MockChunkArchiveRepository_ArchiveFlavor_Call {
	return &MockChunkArchiveRepository_ArchiveFlavor_Call{Call: _e.mock.On("ArchiveFlavor", ctx, chunkID, flavor)}
}

func (_c *MockChunkArchiveRepository_ArchiveFlavor_Call) Run(run func(ctx context.Context, chunkID string, flavor resource.Flavor)) *MockChunkArchiveRepository_ArchiveFlavor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(resource.Flavor))
	})
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveFlavor_Call) Return(_a0 error) *MockChunkArchiveRepository_ArchiveFlavor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveFlavor_Call) RunAndReturn(run func(context.Context, string, resource.Flavor) error) *MockChunkArchiveRepository_ArchiveFlavor_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveFlavorVersion provides a mock function with given fields: ctx, flavorID, version
func (_m *MockChunkArchiveRepository) ArchiveFlavorVersion(ctx context.Context, flavorID string, version resource.FlavorVersion) error {
	ret := _m.Called(ctx, flavorID, version)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveFlavorVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, resource.FlavorVersion) error); ok {
		r0 = rf(ctx, flavorID, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChunkArchiveRepository_ArchiveFlavorVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveFlavorVersion'
type MockChunkArchiveRepository_ArchiveFlavorVersion_Call struct {
	*mock.Call
}

// ArchiveFlavorVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - flavorID string
//   - version resource.FlavorVersion
func (_e *MockChunkArchiveRepository_Expecter) ArchiveFlavorVersion(ctx interface{}, flavorID interface{}, version interface{}) *MockChunkArchiveRepository_ArchiveFlavorVersion_Call {
	return &MockChunkArchiveRepository_ArchiveFlavorVersion_Call{Call: _e.mock.On("ArchiveFlavorVersion", ctx, flavorID, version)}
}

func (_c *MockChunkArchiveRepository_ArchiveFlavorVersion_Call) Run(run func(ctx context.Context, flavorID string, version resource.FlavorVersion)) *MockChunkArchiveRepository_ArchiveFlavorVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(resource.FlavorVersion))
	})
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveFlavorVersion_Call) Return(_a0 error) *MockChunkArchiveRepository_ArchiveFlavorVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunkArchiveRepository_ArchiveFlavorVersion_Call) RunAndReturn(run func(context.Context, string, resource.FlavorVersion) error) *MockChunkArchiveRepository_ArchiveFlavorVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunkArchiveRepository creates a new instance of MockChunkArchiveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkArchiveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkArchiveRepository {
	mock := &MockChunkArchiveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
