// Code generated by mockery. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// MockdatapathSockHandler is an autogenerated mock type for the SockHandler type
type MockdatapathSockHandler struct {
	mock.Mock
}

type MockdatapathSockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdatapathSockHandler) EXPECT() *MockdatapathSockHandler_Expecter {
	return &MockdatapathSockHandler_Expecter{mock: &_m.Mock}
}

// BlockNewConnections provides a mock function with given fields: criCgroupsPath
func (_m *MockdatapathSockHandler) BlockNewConnections(criCgroupsPath string) error {
	ret := _m.Called(criCgroupsPath)

	if len(ret) == 0 {
		panic("no return value specified for BlockNewConnections")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(criCgroupsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdatapathSockHandler_BlockNewConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockNewConnections'
type MockdatapathSockHandler_BlockNewConnections_Call struct {
	*mock.Call
}

// BlockNewConnections is a helper method to define mock.On call
//   - criCgroupsPath string
func (_e *MockdatapathSockHandler_Expecter) BlockNewConnections(criCgroupsPath interface{}) *MockdatapathSockHandler_BlockNewConnections_Call {
	return &MockdatapathSockHandler_BlockNewConnections_Call{Call: _e.mock.On("BlockNewConnections", criCgroupsPath)}
}

func (_c *MockdatapathSockHandler_BlockNewConnections_Call) Run(run func(criCgroupsPath string)) *MockdatapathSockHandler_BlockNewConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdatapathSockHandler_BlockNewConnections_Call) Return(_a0 error) *MockdatapathSockHandler_BlockNewConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdatapathSockHandler_BlockNewConnections_Call) RunAndReturn(run func(string) error) *MockdatapathSockHandler_BlockNewConnections_Call {
	_c.Call.Return(run)
	return _c
}

// DestroySocks provides a mock function with given fields: netnsPath
func (_m *MockdatapathSockHandler) DestroySocks(netnsPath string) error {
	ret := _m.Called(netnsPath)

	if len(ret) == 0 {
		panic("no return value specified for DestroySocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(netnsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdatapathSockHandler_DestroySocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroySocks'
type MockdatapathSockHandler_DestroySocks_Call struct {
	*mock.Call
}

// DestroySocks is a helper method to define mock.On call
//   - netnsPath string
func (_e *MockdatapathSockHandler_Expecter) DestroySocks(netnsPath interface{}) *MockdatapathSockHandler_DestroySocks_Call {
	return &MockdatapathSockHandler_DestroySocks_Call{Call: _e.mock.On("DestroySocks", netnsPath)}
}

func (_c *MockdatapathSockHandler_DestroySocks_Call) Run(run func(netnsPath string)) *MockdatapathSockHandler_DestroySocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockdatapathSockHandler_DestroySocks_Call) Return(_a0 error) *MockdatapathSockHandler_DestroySocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdatapathSockHandler_DestroySocks_Call) RunAndReturn(run func(string) error) *MockdatapathSockHandler_DestroySocks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdatapathSockHandler creates a new instance of MockdatapathSockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdatapathSockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdatapathSockHandler {
	mock := &MockdatapathSockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
