// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/spacechunks/platform/api/platformd/workload/v1alpha1"
)

// MockV1alpha1WorkloadServiceClient is an autogenerated mock type for the WorkloadServiceClient type
type MockV1alpha1WorkloadServiceClient struct {
	mock.Mock
}

type MockV1alpha1WorkloadServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockV1alpha1WorkloadServiceClient) EXPECT() *MockV1alpha1WorkloadServiceClient_Expecter {
	return &MockV1alpha1WorkloadServiceClient_Expecter{mock: &_m.Mock}
}

// RunWorkload provides a mock function with given fields: ctx, in, opts
func (_m *MockV1alpha1WorkloadServiceClient) RunWorkload(ctx context.Context, in *v1alpha1.RunWorkloadRequest, opts ...grpc.CallOption) (*v1alpha1.RunWorkloadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunWorkload")
	}

	var r0 *v1alpha1.RunWorkloadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.RunWorkloadRequest, ...grpc.CallOption) (*v1alpha1.RunWorkloadResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.RunWorkloadRequest, ...grpc.CallOption) *v1alpha1.RunWorkloadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.RunWorkloadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.RunWorkloadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockV1alpha1WorkloadServiceClient_RunWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWorkload'
type MockV1alpha1WorkloadServiceClient_RunWorkload_Call struct {
	*mock.Call
}

// RunWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1alpha1.RunWorkloadRequest
//   - opts ...grpc.CallOption
func (_e *MockV1alpha1WorkloadServiceClient_Expecter) RunWorkload(ctx interface{}, in interface{}, opts ...interface{}) *MockV1alpha1WorkloadServiceClient_RunWorkload_Call {
	return &MockV1alpha1WorkloadServiceClient_RunWorkload_Call{Call: _e.mock.On("RunWorkload",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockV1alpha1WorkloadServiceClient_RunWorkload_Call) Run(run func(ctx context.Context, in *v1alpha1.RunWorkloadRequest, opts ...grpc.CallOption)) *MockV1alpha1WorkloadServiceClient_RunWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1alpha1.RunWorkloadRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockV1alpha1WorkloadServiceClient_RunWorkload_Call) Return(_a0 *v1alpha1.RunWorkloadResponse, _a1 error) *MockV1alpha1WorkloadServiceClient_RunWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockV1alpha1WorkloadServiceClient_RunWorkload_Call) RunAndReturn(run func(context.Context, *v1alpha1.RunWorkloadRequest, ...grpc.CallOption) (*v1alpha1.RunWorkloadResponse, error)) *MockV1alpha1WorkloadServiceClient_RunWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// WorkloadStatus provides a mock function with given fields: ctx, in, opts
func (_m *MockV1alpha1WorkloadServiceClient) WorkloadStatus(ctx context.Context, in *v1alpha1.WorkloadStatusRequest, opts ...grpc.CallOption) (*v1alpha1.WorkloadStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WorkloadStatus")
	}

	var r0 *v1alpha1.WorkloadStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.WorkloadStatusRequest, ...grpc.CallOption) (*v1alpha1.WorkloadStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.WorkloadStatusRequest, ...grpc.CallOption) *v1alpha1.WorkloadStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.WorkloadStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.WorkloadStatusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkloadStatus'
type MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call struct {
	*mock.Call
}

// WorkloadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1alpha1.WorkloadStatusRequest
//   - opts ...grpc.CallOption
func (_e *MockV1alpha1WorkloadServiceClient_Expecter) WorkloadStatus(ctx interface{}, in interface{}, opts ...interface{}) *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call {
	return &MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call{Call: _e.mock.On("WorkloadStatus",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call) Run(run func(ctx context.Context, in *v1alpha1.WorkloadStatusRequest, opts ...grpc.CallOption)) *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1alpha1.WorkloadStatusRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call) Return(_a0 *v1alpha1.WorkloadStatusResponse, _a1 error) *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call) RunAndReturn(run func(context.Context, *v1alpha1.WorkloadStatusRequest, ...grpc.CallOption) (*v1alpha1.WorkloadStatusResponse, error)) *MockV1alpha1WorkloadServiceClient_WorkloadStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockV1alpha1WorkloadServiceClient creates a new instance of MockV1alpha1WorkloadServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockV1alpha1WorkloadServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockV1alpha1WorkloadServiceClient {
	mock := &MockV1alpha1WorkloadServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
