name: test-functional-shared
on:
  pull_request:
permissions:
  contents: read
jobs:
  test-functional:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.0
      - run: make functests-shared